config/routes.rb
Rails.application.routes.draw do
  
  get 'welcome/index'

  resources :users, only: [:create, :update, :show]
  resources :session, only: [:create, :destroy, :update]
  resources :charges

  resources :businesses, only: [:index, :new, :create, :update, :edit, :destroy, :show] do
    resource :design, only: [:new, :create, :update, :show]
    member do 
      get 'claim_business'
      post 'business_claimed'
    end
  end

  namespace :admin do
    resources :users
    resources :businesses
  end
  
  get '/class_register', to: 'businesses#class', as: :signup
  match '/register_class', to: 'businesses#register_class', via: 'POST'
  get 'home', to: 'welcome#index', as: :home
  get 'login', to: 'session#new', as: :login
  get 'register', to: 'users#new', as: :register

  root 'welcome#index'

  get '/auth/:provider/callback', :to => 'session#create'
  delete '/logout', to: 'session#destroy'

  get '/businesses/:business_id/design/', to: 'designs#create'
  p '/businesses/:business_id/design/', to: 'designs#create'

end

app/controllers/admin/businesses_controller.rb
class Admin::BusinessesController < ApplicationController
  before_action :require_admin

  def require_admin
    if current_user.user_type != "superuser"
      flash[:error] = "Unauthorized Access"
      redirect_to '/'

    end
  end

  def new
    @business = Business.new
  end
  def index
    @businesses = Business.order("name").page(params[:page])
  end

  def edit
    @business = Business.find(params[:id])
  end

  def update
    @business = Business.find(params[:id])
    
    @user = User.find(assign_business_params[:user_id])
    #binding.pry
    if @user
      @user.user_type = "owner"
      # binding.pry
      @business.user_id = assign_business_params[:user_id]
      @business.save
      redirect_to admin_businesses_path
    else
      flash[:alert] = "Invalid"
      render :edit
    end

  end
  protected
  def assign_business_params
    params.require(:business).permit(:user_id)
  end


end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController
  helper BusinessHelper

  def new
    @business = Business.new
  end

  def create
    @business = Business.new(business_params)
    @business.user_id = current_user.id
    if @business.save
      redirect_to @business
    else
      render :new
    end
  end

  def index
    @businesses = Business.all

    if params[:search]
      @businesses = @businesses.check_query(params[:search])
    end
  end

  def show
    @business = Business.find(params[:id])
  end

  def edit
    @business = Business.find(params[:id])
  end

  def update
    @business = Business.find(params[:id])
    if @business.update_attributes(business_params)
      redirect_to business_path(@business)
    else
      render :edit
    end

  end

  def format_id(string)
    string.match(/\d{1,}/)
  end

  def claim_business
    @business = Business.find(params[:id])
  end

  def business_claimed
    user_id = format_id("#{params[:user_id]}")
    name = params[:name]
    email = params[:email]
    business_name = params[:business_name]
    business_address = params[:business_address]
    business_phone = params[:business_phone]
    comments = params[:comments]

    OwnerMailer.claim_business_email(user_id, name, email, business_name, business_address, business_phone, comments).deliver
    flash[:notice] = "Business claim request has been sent."
    redirect_to business_path
  end


  def register_class
    businessID = format_id("#{params[:business_id]}")
    @business = Business.find(businessID[0].to_i)
    name = params[:name]
    phone_number = params[:phonenumber]
    email = params[:email]
    class_name = params[:class_name]
    class_date = params[:class_date]
    comments = params[:comments]
    
    ClassMailer.class_signup_email(name, phone_number, email, class_name, class_date, comments, @business).deliver
    flash[:notice] = "Class signup has been sent to the business."
    redirect_to business_path(@business.id)
  end

  protected

  def business_params
    params.require(:business).permit(:category, :name, :phone, :email, :photo, :description, :website, :address, :city, :postal_code, :province, :country)
  end

end

app/helpers/admin/businesses_helper.rb
module Admin::BusinessesHelper
end

app/helpers/business_helper.rb
module BusinessHelper
  #@last_group_of_featured = [] 
  def format_id(string)
    string.match(/\d/)
  end

  # def get_last_featured(a_business)
  #   if @last_group_of_featured.length >= 3
  #     @last_group_of_featured.shift
  #     @last_group_of_featured << a_business if a_business.featured == true
  #   else
  #     @last_group_of_featured << a_business if a_business.featured == true
  #   end
  # end

  # def return_last_featured
  #   return @last_group_of_featured
  # end
  
end

app/views/businesses/_form.html.erb
<main>
<br>
<%= form_for @business, :html => {:multipart => true} do |f| %>
  <% if @business.errors.any? %>
    <div>
      <%= pluralize(@business.errors.count, "error") %> prevented this business from being submitted:
        <ul>
          <%= @business.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
    </div>
  <% end %>
  <div class="container-content">
    <div class="container">
      <br>
      <div>
        <%= f.label "category" %>
        <%= f.text_field "category" %>
      </div>
      <div>
        <%= f.label "name" %>
        <%= f.text_field "name" %>
      </div>
      <div>
        <%= f.label "phone" %>
        <%= f.text_field "phone" %>
      </div>
      <div>
        <%= f.label "email" %>
        <%= f.text_field "email" %>
      </div>
      <div>
        <%= f.label "description" %>
        <%= f.text_field "description" %>
      </div>
      <div>
        <%= f.label "website" %>
        <%= f.text_field "website" %>
      </div>
      <div>
        <%= f.label "address" %>
        <%= f.text_field "address" %>
      </div>
      <div>
        <%= f.label "city" %>
        <%= f.text_field "city" %>
      </div>
      <div>
        <%= f.label "postal_code" %>
        <%= f.text_field "postal_code" %>
      </div>
      <div>
        <%= f.label "province" %>
        <%= f.text_field "province" %>
      </div>
      <div>
        <%= f.label "country" %>
        <%= f.text_field "country" %>
      </div>
      <div><%= f.file_field :photo %></div>
      <br>
      <div>
        <%= f.submit "Submit", :class => "download-button btn waves-effect waves-light teal lighten-1 hoverable"  %>
      </div>
      <br>
    </div>
  </div>
<% end %>
</main>

app/views/businesses/claim_business.html.erb
<main>
<div class="container-content">
  <div class="container">
  <br>
  <h3 class="flow-text">Claim Form For <%= params[:name] %>:</h3>
  <br>
    <%= form_tag(business_claimed_business_path) do %>
    <%= hidden_field :user_id, :value => current_user.id %> 
      <div class="form-group">
        <%= label_tag 'name', 'Name' %>
        <%= text_field_tag 'name', nil, class: 'form-control', placeholder: 'Your Name' %>
      </div>
      <div class="form-group">
        <%= label_tag 'email', 'Email' %>
        <%= email_field_tag 'email', nil, class: 'form-control', placeholder: 'Your Email Address' %>
      </div>
      <div class="form-group">

        <%= label_tag 'business_name', 'Business Name' %>
        <%= text_field_tag 'business_name', nil, class: 'form-control', placeholder: 'The Business name you wish to claim' %>
      </div>
      <div class="form-group">
        <%= label_tag 'business_address', 'Business Address' %>
        <%= text_field_tag 'business_address', nil, class: 'form-control', rows: 4, placeholder: 'Address of Business' %>
      </div>
      <div class="form-group">
        <%= label_tag 'business_phone', 'Phone Number' %>
        <%= text_field_tag 'business_phone', nil, class: 'form-control', rows: 4, placeholder: 'Business Phone Number' %>
      </div>
      <div class="form-group">
        <%= label_tag 'comments', 'Comments' %>
        <%= text_field_tag 'comments', nil, class: 'form-control', rows: 4, placeholder: 'Comments...' %>
       </div>
       <br>
       <%= submit_tag nil, class: 'btn btn-default btn-about pull-right' %>
    <% end %>
    <br>
  </div>
</div>
</main>

app/views/businesses/class.html.erb
<script>
$(function() {
  // $('#classBtn').on('click', function(event) {
  //   event.preventDefault();
  // })
  $('.payments').show();

  var handler = StripeCheckout.configure({
  key: 'pk_test_hD5PFgoKwJUUZo6g5yWvZbkE',
  token: function(token) {
    // Use the token to create the charge with a server-side script.
    // You can access the token ID with `token.id`
  }
  });

  $(document).on('click', '#classBtn',function(e) {
    e.preventDefault()
    console.log('click')
    // Open Checkout with further options

    handler.open({
      name: '<%= Business.find(params[:business]).name %>',
      currency: "cad",
      amount: 500,
      closed: function(){ $('#sign-upClass').submit() }
    });
  });

// Close Checkout on page navigation
  $(window).on('popstate', function() {
    handler.close();
  });
})

</script>
<main>
  <div class="container-content">
  <br>
    <h3 class="center flow-text">Let's Sign You Up For A Class</h3>
    <div class="container">
      <%= form_tag(register_class_path, {:id => "sign-upClass"}) do %>
       <%= hidden_field :business_id, :value => params[:business] %> 
        <div class="form-group">
          <%= label_tag 'name', 'Name' %>
          <%= text_field_tag 'name', nil, class: 'form-control', placeholder: 'Your Name' %>
        </div>
        <div class="form-group">
          <%= label_tag 'phone_number', 'Phone Number' %>
          <%= text_field_tag 'phonenumber', nil, class: 'form-control', placeholder: 'Your Phone number' %>
        </div>
        <div class="form-group">
          <%= label_tag 'email', 'Email' %>
          <%= email_field_tag 'email', nil, class: 'form-control', placeholder: 'Your Email Address' %>
        </div>
        <div class="form-group">
          <%= label_tag 'class_date', 'Class Date' %>
          <%= date_field 'class_date', nil, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= label_tag 'class_name', 'Class Name' %>
          <%= text_field_tag 'class_name', nil, class: 'form-control', placeholder: 'Which class do you want to take?' %>
        </div>
        <div class="form-group">
          <%= label_tag 'comments', 'Comments' %>
          <%= text_field_tag 'comments', nil, class: 'form-control', rows: 4, placeholder: 'Anything else we should know?' %>
         </div>
         <br>
         <button class='btn btn-default btn-about pull-right' id='classBtn'>Submit</button>
         <br>
      <% end %>
    </div>
  </div>
  <div class="stripePayment">

  </div>
</main>

app/views/businesses/edit.html.erb
<%= render 'form' %>

app/views/businesses/index.html.erb
<main>
  <div class="container about">
    <br>
    <h5 class="flow-text">Yoga Studios</h5>
    <h6>British Columbia</h6>
    <hr>
    <% @businesses.each do |business| %>
      <div class="container">
        <div class="card-business hoverable">
          <div class="card-header-business">
            <% if business.photo_scraped %>
              <img src=<%= business.photo_scraped %>>
            <% else %>
              <%= image_tag('default.png') %>
            <% end %>
          </div>
          <div class="card-content-business">
            <h3 class="flow-text center-align"><%=link_to business.name, business_path(business), :class => "teal-text text-lighten-1"%></h3>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</main>

app/views/businesses/index_2.html.erb
<div class="intro deep-orange lighten-2 z-depth-1">
  <h1 class="grey-text text-lighten-5">Almanak</h1>
  <h5 clas="grey lighten-4 grey-text text-darken-1">Your favorite business directory</h5>
</div>

 <div class="container about">
  <h5>about us</h5>
  <h6>let us introduce ourself</h6>
  <hr>
  <div class="row">
    <div class="col s12 m4 l4">
      <h6>Story</h6>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
    </div>
    <div class="col s12 m4 l4">
      <h6>Profile</h6>
      <div class="card blue-grey darken-1">
        <div class="card-content white-text">
          <img src="http://labs.qnimate.com/portfolio-materialize/images/profile.png" width="64" height="64">
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore.</p>
        </div>
        <div class="card-action">
          <a href="#">Link</a>
          <a href='#'>Link</a>
        </div>
      </div>
    </div>
    <div class="col s12 m4 l4">
      <h6>current jobs</h6>
      <ul class="collapsible">
        <li class="active">
          <div class="collapsible-header"><i class="mdi-av-web"></i>Designer</div>
          <div class="collapsible-body"><p>Lorem ipsum dolor sit amet.</p></div>
        </li>
        <li>
          <div class="collapsible-header"><i class="mdi-editor-format-align-justify"></i>Developer</div>
          <div class="collapsible-body"><p>Lorem ipsum dolor sit amet.</p></div>
        </li>
        <li>
          <div class="collapsible-header"><i class="mdi-av-play-shopping-bag"></i>Video Editor</div>
          <div class="collapsible-body"><p>Lorem ipsum dolor sit amet.</p></div>
        </li>
        <li>
          <div class="collapsible-header"><i class="mdi-editor-insert-comment"></i>Support Asst.</div>
          <div class="collapsible-body"><p>Lorem ipsum dolor sit amet.</p></div>
        </li>
      </ul>
    </div>
  </div>
</div>

<div class="container portfolio">
  <h5>portfolio</h5>
  <h6>MY LATEST PROJECTS</h6>
  <hr>
  <div class="row">
    <div class="col s12 m12 l12 portfolio-holder">
      <img class="materialboxed" src="http://labs.qnimate.com/portfolio-materialize/images/project.png">
      <img class="materialboxed" src="http://labs.qnimate.com/portfolio-materialize/images/project.png">
      <img class="materialboxed" src="http://labs.qnimate.com/portfolio-materialize/images/project.png">
      <img class="materialboxed" src="http://labs.qnimate.com/portfolio-materialize/images/project.png">
      <img class="materialboxed" src="http://labs.qnimate.com/portfolio-materialize/images/project.png">
      <img class="materialboxed" src="http://labs.qnimate.com/portfolio-materialize/images/project.png">
    </div>
  </div>
</div>
<div class="container contact">
  <h5>contact</h5>
  <h6>get in touch with me</h6>
  <hr>
  <div class="row">
    <div class="col s12 m6 l6">
      <div class="row">
        <form class="col s12">
          <div class="row">
            <div class="input-field col s6">
              <input id="first_name" type="text" class="validate">
              <label for="first_name">First Name</label>
            </div>
            <div class="input-field col s6">
              <input id="last_name" type="text" class="validate">
              <label for="last_name">Last Name</label>
            </div>
          </div>
          <div class="row">
            <div class="input-field col s12">
              <input id="email" type="email" class="validate">
              <label for="email">E-Mail</label>
            </div>
          </div>
          <textarea class="materialize-textarea" placeholder="Your Message" required></textarea>
          <button class="btn waves-effect waves-light" type="submit" name="action">Submit
            <i class="mdi-content-send right"></i>
          </button>
        </form>
      </div>
    </div>
    <div class="col s12 m6 l6 contact-holder">
      <h6 class="mdi-action-home">Address</h6>
      <p>Nr. 6, 21 Awesome Street, London, UK</p>
      <h6 class="mdi-hardware-phone-android">Phone Number</h6>
      <p>+91 9912776151</p>
      <h6 class="mdi-action-open-in-browser">Website</h6>
      <p>qnimate.com</p>
    </div>
  </div>
</div>

  
   

<h3>Gyms In Vancouver!</h3>
<%= link_to "Create a new gym!", new_business_path %>
<br>
<% @businesses.each do |business| %>
  <center>
<div class="container">
  <div class="row">
    <div class="col s12 m4">
      <div class="card grey lighten-5">
        <div class="card-content black-text">
          <span class="card-title"><%= link_to business.name, business.website %></span>
          <br>
            <% if business.photo %>
              <%= link_to image_tag(business.photo), business_path(business) %>
            <% else %>
              <div><%= link_to image_tag('default.png'), business_path(business) %></div>
            <% end %>
            <br>
            <p><%= business.address %>, <%= business.city %>, <%= business.province %>, <%= business.postal_code %></p>
            <br>
            <p><%= business.phone %></p>
        </div>
        <div class="card-action">
          <%= link_to "Business Page", business_path(business) %>
        </div>
      </div>
    </div>
  </div>
</div>
  </center>
<% end %>


<footer>
  <div class="footer-copyright">
    <div class="container">
    © 2014 Copyright Text
    <a class="grey-text text-lighten-4 right" href="#!">Link</a>
    </div>
  </div>
</footer>









<% @businesses.each do |business| %>

  <div class="row">
    <div class="col s12 m4 l4">
      <h6>Description</h6>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
    </div>
    <div class="col s12 m4 l4">
      <h6 class="blue-grey-text text-darken-1"><%=link_to business.name, business_path(business)%></h6>
      <div class="card blue-grey darken-1 hoverable">
        <div class="card-content white-text">
          <br>
          <% if business.photo_scraped %>
            <img class="business_thumbnail" src=<%= business.photo_scraped %>>
          <% else %>
            <img class="business_thumbnail" <%= image_tag('default.png') %>
          <% end %>
        </div>
      </div>
    </div>
    <div class="col s12 m4 l4">
      <h6>Information</h6>
      <ul class="collapsible hoverable">
        <li class="active">
          <div class="collapsible-header"><i class="mdi-maps-my-location"></i>Address</div>
          <div class="collapsible-body"><p><%= business.address %>, <%= business.city %>, <%= business.province %>, <%= business.postal_code %></p></div>
        </li>
        <li>
          <div class="collapsible-header"><i class="mdi-communication-phone"></i>Phone</div>
          <div class="collapsible-body"><p><%= business.phone %></p></div>
        </li>
        <li>
          <div class="collapsible-header"><i class="mdi-av-web"></i>Website</div>
          <div class="collapsible-body">
            <% if current_user.id == business.user_id %>
              <p><%= link_to 'Create page', new_business_design_path(:business_id => business.id) %></p>
            <% else %>
              <p><%= link_to business.name, business.website %></p>
            <% end %>
          </div>
        </li>
      </ul>
    </div>
  </div>
  <% end %>

app/views/businesses/new.html.erb
<%= render 'form' %>

app/views/businesses/show.html.erb
<main>
<div class="container about">
<br>
  <h5><%=@business.name%></h5>
  <h6><%= @business.city %>, <%= @business.province %></h6>
  <% if current_user %>
    <% if @business.user_id %>
      <h6><%= link_to 'Sign Up for Class', signup_path(:business => @business.id), :class => "download-button btn-large waves-effect waves-light red lighten-2 hoverable" %></h6>
      <% if @business.user_id == current_user.id %>
        <h6><%= link_to 'Edit Business Info', edit_business_path, :class => "download-button btn-large waves-effect waves-light red lighten-2 hoverable" %></h6>
      <% end %>
    <% else %>
      <h6><%= link_to 'Claim Business', claim_business_business_path(:name => @business.name), :class => "download-button btn-large waves-effect waves-light red lighten-2 hoverable" %></h6>
    <% end %>
  <% else %>
    <h6><%= link_to 'Sign-in To Claim Business', login_path, :class => "download-button btn-large waves-effect waves-light red lighten-2 hoverable"  %></h6>
  <% end %>
  <hr>
  
  <div class="row">
    <div class="col s12 m4 l4">
      <h6>Description</h6>
      <p>Our specialized team has been chosen to represent their respective philosophies based on their ability to bridge the gap between traditional systems of medicine or healing and make them relevant to you.</p>
      <p>A practice based not merely on a series of postures, but a philosophy that integrates the Seven Spiritual Laws of Yoga</p>
    </div>
    <div class="col s12 m4 l4">
      <h6 class="blue-grey-text text-darken-1"><%=@business.name%></h6>
      <div class="card blue-grey darken-1 hoverable">
        <div class="card-content white-text">
          <br>
          <% if @business.photo_scraped %>
            <img class="business_thumbnail" src=<%= @business.photo_scraped %>>
          <% else %>
            <img class="business_thumbnail" <%= image_tag('default.png') %>
          <% end %>
        </div>
      </div>
    </div>
    <div class="col s12 m4 l4">
      <h6>Information</h6>
      <ul class="collapsible hoverable">
        <li class="active">
          <div class="collapsible-header"><i class="mdi-maps-my-location"></i>Address</div>
          <div class="collapsible-body"><p><%= @business.address %>, <%= @business.city %>, <%= @business.province %>, <%= @business.postal_code %></p></div>
        </li>
        <li>
          <div class="collapsible-header"><i class="mdi-communication-phone"></i>Phone</div>
          <div class="collapsible-body"><p><%= @business.phone %></p></div>
        </li>
        <li>
          <div class="collapsible-header"><i class="mdi-av-web"></i>Website</div>
          <% if @business.website == ""%>
            <div class="collapsible-body"><p><%= link_to 'Create a page', new_business_design_path %></p></div>
          <% else %>
            <div class="collapsible-body"><p><%= link_to @business.name, @business.website %></p></div>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
  <div class="container">
    <center>
    <%= link_to image_tag("http://maps.google.com/maps/api/staticmap?size=2048x300&sensor=false&zoom=16&markers=#{@business.latitude}%2C#{@business.longitude}", {:class => 'maps-img hoverable z-depth-1'}), @business.gmaps_url, target: '_blank'  %>
    </center>
  </div>
  <br>
</div>
</main>