config/routes.rb
Rails.application.routes.draw do
  
  get 'welcome/index'

  resources :users, only: [:create, :update, :show]
  resources :session, only: [:create, :destroy, :update]
  resources :charges

  resources :businesses, only: [:index, :new, :create, :update, :edit, :destroy, :show] do
    resource :design, only: [:new, :create, :update, :show]
    member do 
      get 'claim_business'
      post 'business_claimed'
    end
  end

  namespace :admin do
    resources :users
    resources :businesses
  end
  
  get '/class_register', to: 'businesses#class', as: :signup
  match '/register_class', to: 'businesses#register_class', via: 'POST'
  get 'home', to: 'welcome#index', as: :home
  get 'login', to: 'session#new', as: :login
  get 'register', to: 'users#new', as: :register

  root 'welcome#index'

  get '/auth/:provider/callback', :to => 'session#create'
  delete '/logout', to: 'session#destroy'

  get '/businesses/:business_id/design/', to: 'designs#create'
  p '/businesses/:business_id/design/', to: 'designs#create'

end

app/controllers/admin/businesses_controller.rb
class Admin::BusinessesController < ApplicationController
  before_action :require_admin

  def require_admin
    if current_user.user_type != "superuser"
      flash[:error] = "Unauthorized Access"
      redirect_to '/'

    end
  end

  def new
    @business = Business.new
  end
  def index
    @businesses = Business.order("name").page(params[:page])
  end

  def edit
    @business = Business.find(params[:id])
  end

  def update
    @business = Business.find(params[:id])
    
    @user = User.find(assign_business_params[:user_id])
    #binding.pry
    if @user
      @user.user_type = "owner"
      # binding.pry
      @business.user_id = assign_business_params[:user_id]
      @business.save
      redirect_to admin_businesses_path
    else
      flash[:alert] = "Invalid"
      render :edit
    end

  end
  protected
  def assign_business_params
    params.require(:business).permit(:user_id)
  end


end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController
  helper BusinessHelper

  def new
    @business = Business.new
  end

  def create
    @business = Business.new(business_params)
    @business.user_id = current_user.id
    if @business.save
      redirect_to @business
    else
      render :new
    end
  end

  def index
    @businesses = Business.all

    if params[:search]
      @businesses = @businesses.check_query(params[:search])
    end
  end

  def show
    @business = Business.find(params[:id])
  end

  def edit
    @business = Business.find(params[:id])
  end

  def update
    @business = Business.find(params[:id])
    if @business.update_attributes(business_params)
      redirect_to business_path(@business)
    else
      render :edit
    end

  end

  def format_id(string)
    string.match(/\d{1,}/)
  end

  def claim_business
    @business = Business.find(params[:id])
  end

  def business_claimed
    user_id = format_id("#{params[:user_id]}")
    name = params[:name]
    email = params[:email]
    business_name = params[:business_name]
    business_address = params[:business_address]
    business_phone = params[:business_phone]
    comments = params[:comments]

    OwnerMailer.claim_business_email(user_id, name, email, business_name, business_address, business_phone, comments).deliver
    flash[:notice] = "Business claim request has been sent."
    redirect_to business_path
  end


  def register_class
    businessID = format_id("#{params[:business_id]}")
    @business = Business.find(businessID[0].to_i)
    name = params[:name]
    phone_number = params[:phonenumber]
    email = params[:email]
    class_name = params[:class_name]
    class_date = params[:class_date]
    comments = params[:comments]
    
    ClassMailer.class_signup_email(name, phone_number, email, class_name, class_date, comments, @business).deliver
    flash[:notice] = "Class signup has been sent to the business."
    redirect_to business_path(@business.id)
  end

  protected

  def business_params
    params.require(:business).permit(:category, :name, :phone, :email, :photo, :description, :website, :address, :city, :postal_code, :province, :country)
  end

end

app/helpers/admin/businesses_helper.rb
module Admin::BusinessesHelper
end

app/helpers/business_helper.rb
module BusinessHelper
  #@last_group_of_featured = [] 
  def format_id(string)
    string.match(/\d/)
  end

  # def get_last_featured(a_business)
  #   if @last_group_of_featured.length >= 3
  #     @last_group_of_featured.shift
  #     @last_group_of_featured << a_business if a_business.featured == true
  #   else
  #     @last_group_of_featured << a_business if a_business.featured == true
  #   end
  # end

  # def return_last_featured
  #   return @last_group_of_featured
  # end
  
end

app/views/admin/businesses/_form.html.erb
<main>
<%= form_for [:admin,@business] do |f| %>
  <% if @business.errors.any? %>
    <div>
      <%= pluralize(@business.errors.count, "error") %> prevented the business from assigned to user
      <ul>
        <% @business.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= f.label "user id" %>
    <%= f.number_field "user_id" %>
  </div>
  
  <div><%= f.submit "Submit", :class => "download-button btn waves-effect waves-light teal lighten-1 hoverable" %></div>
<% end %>
<br>
</main>

app/views/admin/businesses/edit.html.erb
<main>
<div class="container">
<br>
<h3 class="flow-text">Assign User To Business</h3>
<%= render 'form' %>
</div>
</main>

app/views/admin/businesses/index.html.erb
<main>
<div class="container">
<h3 class="flow-text">Admin Business Management Page</h3>
<%= paginate @businesses %>

  <table class="hoverable bordered z-depth-1">
    <thead>
      <tr>
          <th>Name</th>
          <th>Email</th>
          <th>Edit</th>
      </tr>
    </thead>
    <% @businesses.each do |business| %>
    <tbody>
      <tr>
        <td><%= business.name %></td>
        <td><%= business.email %></td>
        <td><%= link_to "Assign To Business" , edit_admin_business_path(business), :class => "download-button btn waves-effect waves-light teal lighten-1 hoverable" %></td>
      </tr>
    </tbody>
    <% end %>
  </table>
  <br>
</div>
</main>