config/routes.rb
Rails.application.routes.draw do
  
  get 'welcome/index'

  resources :users, only: [:create, :update, :show]
  resources :session, only: [:create, :destroy, :update]
  resources :charges

  resources :businesses, only: [:index, :new, :create, :update, :edit, :destroy, :show] do
    resource :design, only: [:new, :create, :update, :show]
    member do 
      get 'claim_business'
      post 'business_claimed'
    end
  end

  namespace :admin do
    resources :users
    resources :businesses
  end
  
  get '/class_register', to: 'businesses#class', as: :signup
  match '/register_class', to: 'businesses#register_class', via: 'POST'
  get 'home', to: 'welcome#index', as: :home
  get 'login', to: 'session#new', as: :login
  get 'register', to: 'users#new', as: :register

  root 'welcome#index'

  get '/auth/:provider/callback', :to => 'session#create'
  delete '/logout', to: 'session#destroy'

  get '/businesses/:business_id/design/', to: 'designs#create'
  p '/businesses/:business_id/design/', to: 'designs#create'

end

app/models/user.rb
class User < ActiveRecord::Base
  has_one :business
  # has_secure_password
  # validates :firstname, presence: true
  # validates :lastname, presence: true
  # validates :email, presence: true, uniqueness: true

  def full_name
    "#{first_name} #{last_name}"
  end

  class << self
    def from_omniauth(auth_hash)
      user = find_or_create_by(uid: auth_hash['uid'], provider: auth_hash['provider'])
      user.name = auth_hash['info']['name']
      user.photo = auth_hash['info']['image']
      user.first_name = auth_hash['info']['first_name']
      user.last_name = auth_hash['info']['last_name']
      user.email = auth_hash['info']['email']

      user.save!
      user
    end
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :require_admin

  def require_admin
    if current_user.user_type != "superuser" 
      flash[:error] ="Unauthorized Access"
      redirect_to '/'
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:id] = @user.id
      redirect_to '/'
    else
      render :new
    end
  end

  def index
    @users = User.order("id").page(params[:page])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      redirect_to admin_users_path
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    if @user.destroy
      #UserMailer.delete_email(@user).deliver
      redirect_to admin_users_path, notice: "User deleted from database"
    else
      redirect_to admin_users_path, notice: "can't get rid of me bruh"
    end
  end

  protected

  def user_params
    params.require(:user).permit(:email, :first_name, :last_name, :user_type, :password, :password_confirmation)
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to '/'
    else
      render :new
    end
  end

  # def index
  # end

  protected

  def user_params
    params.require(:user).permit(:email, :first_name, :last_name, :password, :password_confirmation)
  end
  
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_form.html.erb
<main>
<%= form_for [:admin, @user] do |f| %>
  <% if @user.errors.any? %>
    <div>
      <%= pluralize(@user.errors.count, "error") %> prevented the account from being created:
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= f.label "email" %>
    <%= f.text_field(:email) %>
  </div>
  <div>
    <%= f.label "firstname", "First Name" %><br>
    <%= f.text_field(:first_name) %>
  </div>
  <div>
    <%= f.label "lastname", "Last Name" %><br>
    <%= f.text_field(:last_name) %>
  </div>
   <div>
    <%= f.label "name", "Full name" %><br>
    <%= f.text_field(:name) %>
  </div>
  <div>
    <%= f.label "user_type", "User Type" %><br>
    <%= f.select(:user_type,["customer", "owner"], {}, {:class => 'browser-default'}) %><br>
  </div>
  <div><%= f.submit "Submit" %></div>
<% end %>

</main>

app/views/admin/users/edit.html.erb
<div class="container">
<h3>Edit User</h3>
<%= render 'form' %>
</div>

app/views/admin/users/index.html.erb
<main>
  <div class="container">
    <h3 class="flow-text">Admin User Management</h3>
    <%= paginate @users %>
    <table class="hoverable bordered z-depth-1">
      <thead>
        <tr>
            <th>Name</th>
            <th>Email</th>
            <th>Edit</th>
            <th>Delete</th>
        </tr>
      </thead>
      <% @users.each do |user| %>
      <tbody>
        <% if user.first_name.to_s == '' %>
          <tr>
            <td><%= user.name  %></td>
            <td><%= user.email %></td>
            <td><%= link_to "Edit" , edit_admin_user_path(user), :class => "download-button btn waves-effect waves-light teal lighten-1 hoverable"  %></td>
            <td><%= link_to "Delete", admin_user_path(user), method: :delete , :class => "download-button btn waves-effect waves-light teal lighten-1 hoverable" %></td>
          </tr>  
        <% else %>
          <tr>
            <td><%= user.first_name%> <%= user.last_name%></td>
            <td><%= user.email %></td>
            <td><%= link_to "Edit" , edit_admin_user_path(user), :class => "download-button btn waves-effect waves-light teal lighten-1 hoverable"  %></td>
            <td><%= link_to "Delete", admin_user_path(user), method: :delete , :class => "download-button btn waves-effect waves-light teal lighten-1 hoverable" %></td>
          </tr>   
        <% end %>
      </tbody>
      <% end %>
    </table>
    <br>
    <%= link_to "Create User", new_admin_user_path, :class => "download-button btn-large waves-effect waves-light teal lighten-1 hoverable" %>
    <br>
  </div>
</main>

app/views/admin/users/new.html.erb
<div class="container">
<h3>Create User</h3>
<%= render 'form' %>
</div>