config/routes.rb
Rails.application.routes.draw do
  
  get 'welcome/index'

  resources :users, only: [:create, :update, :show]
  resources :session, only: [:create, :destroy, :update]
  resources :charges

  resources :businesses, only: [:index, :new, :create, :update, :edit, :destroy, :show] do
    resource :design, only: [:new, :create, :update, :show]
    member do 
      get 'claim_business'
      post 'business_claimed'
    end
  end

  namespace :admin do
    resources :users
    resources :businesses
  end
  
  get '/class_register', to: 'businesses#class', as: :signup
  match '/register_class', to: 'businesses#register_class', via: 'POST'
  get 'home', to: 'welcome#index', as: :home
  get 'login', to: 'session#new', as: :login
  get 'register', to: 'users#new', as: :register

  root 'welcome#index'

  get '/auth/:provider/callback', :to => 'session#create'
  delete '/logout', to: 'session#destroy'

  get '/businesses/:business_id/design/', to: 'designs#create'
  p '/businesses/:business_id/design/', to: 'designs#create'

end

app/views/layouts/_footer.html.erb
<footer class="page-footer teal">
  <div class="container">
    <div class="row">
      <div class="col l6 s12">
        <h5 class="white-text">Company Bio</h5>
        <p class="grey-text text-lighten-4">We are a team of Lighthouse Labs' students working on this project.</p>
      </div>
    </div>
  </div>
  <div class="footer-copyright">
    <div class="container">
      Made by Sonny, Joey and Henry</a>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
<nav class="teal lighten-1 navbar-fixed" role="navigation">
  <div class="nav-wrapper">
    <div class="row">
      <div class="almanak-logo col s12 m1 left">
        <h4><a href="/" class="logo">
          <img class="logo-hover" src="<%= asset_path('book2.png') %>">
        </a></h4>
      </div>
      <div class="col sm12 m5 input-field">
          <%= form_tag(businesses_path, method: "get", :class => "nav-search")  do %> 
            <%= text_field_tag :search, nil , placeholder: "Search", class:"nav-search-text-field"%>

          <% end %>
      <!-- <i class="mdi-action-search"></i> -->
      </div>
      
      <div class="col s12 m4 right">
        <div id="nav-mobile" class="right">
          <% if current_user %>
            <ul>
            <!-- Twitter and facebook save names differently -->
            <% if current_user.full_name == " " %>
              <% if current_user && current_user.user_type == "superuser" %>
                <li class="avatar-name dropdown-button" data-activates='dropdown1'>Admin : <%= current_user.name %> </li>
                <ul id='dropdown1' class='dropdown-content'>
                  <li><%= link_to 'Users', admin_users_path %></li>
                  <li class="divider"></li>
                  <li><%= link_to 'Businesses', admin_businesses_path %></li> 
                </ul>
              <% elsif current_user && current_user.user_type == "owner"%>
                <li class="avatar-name dropdown-button" data-activates='dropdown3'>Owner : <%= current_user.name %> </li>
                <ul id='dropdown3' class='dropdown-content'>
                  <li><%= link_to 'Customers', businesses_path %></li>
                  <li class="divider"></li>
                  <li><%= link_to 'Edit Page', businesses_path %></li> 
                </ul>
              <% else %>
                <li class="avatar-name"><%= current_user.name %> </li>  
              <% end %>
            <% else %>
              <% if current_user && current_user.user_type == "superuser" %>
                <li class="avatar-name dropdown-button" data-activates='dropdown1'>Admin : <%= current_user.full_name %> </li>
                <ul id='dropdown1' class='dropdown-content'>
                  <li><%= link_to 'Users', admin_users_path %></li>
                  <li class="divider"></li>
                  <li><%= link_to 'Businesses', admin_businesses_path %></li> 
                </ul>
              <% elsif current_user && current_user.user_type == "owner"%>
                <li class="avatar-name dropdown-button" data-activates='dropdown3'>Owner : <%= current_user.name %> </li>
                <ul id='dropdown3' class='dropdown-content'>
                  <li><%= link_to 'Customers', businesses_path %></li>
                  <li class="divider"></li>
                  <li><%= link_to 'Edit Page', businesses_path %></li> 
                </ul>
              <% else %>
                <li class="avatar-name"><%= current_user.name %> </li>  
              <% end %>
            <% end %>
              <li class="avatar_thumbnail"><%= image_tag current_user.photo, alt: current_user.name %></li>
              <li><%= link_to 'Log Out', logout_path, method: :delete %></li>
            </ul>
          <% else %>
            <ul class="right">
              <li>Login With</li>
              <!-- link_to image_tag('facebook1.png') -->
              <li class="tw-fb-logo"><%= link_to image_tag('twitter.png'), '/auth/twitter' %></li>
              <li class="tw-fb-logo"><%= link_to image_tag('facebook.png'), '/auth/facebook' %></li>
            </ul>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</nav>
</header>

app/views/layouts/_header2.html.erb
<small>
  <% if current_user %>
    <% if current_user.user_type == "superuser" %>
      Signed in as <%= current_user.full_name %> (<%= link_to "Log out", session_path("current"), method: :delete %>) (<%= link_to "Admin User Management", admin_users_path %>) (<%= link_to "Admin business management", admin_businesses_path %>)
    <% else %>
      Signed in as <%= current_user.full_name %> (<%= link_to "Log out", session_path("current"), method: :delete %>)
    <% end %>
  <% else %>
    <%= link_to "Log in", login_path %> | <%= link_to "Register", register_path %>
  <% end %>
</small>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bobloblaw</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>
  <script src="https://checkout.stripe.com/checkout.js"></script>
</head>
<body>
<% if @show_navbar %>
  <%= render 'layouts/header' unless @disable_nav %>
  <%= yield %>
  <%= render 'layouts/footer' %>
<% else %>
  <%= yield %>
<% end %>

</body>
</html>